<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<style>
    @page{
        margin:20px;
    }

    body{
        font-family: DejaVu Sans, sans-serif;
        font-size:11px;
        color:#222;
    }

    table{
        border-collapse:collapse;
        width:100%;
    }

    .main-table,
    .legend-table{
        border:1px solid #444;
    }

    .main-table th,
    .main-table td,
    .legend-table td{
        border:1px solid #444;
        padding:6px;
        text-align:center;
        vertical-align:middle;
    }

    .title{
        font-size:24px;
        font-weight:bold;
        text-align:left;
        padding:12px;
    }

    .department{
        font-size:20px;
        color:#003cff;
        font-weight:bold;
    }

    .header{
        background:#efefef;
        font-weight:bold;
    }

    .skill-header{
        background:#f7f7f7;
        font-weight:bold;
        font-size:10px;
    }

    .employee{
        text-align:left;
    }

    .circle{
        width:18px;
        height:18px;
        border-radius:50%;
        display:inline-block;
        background:#ff7300;
    }

    .legend-title{
        font-size:18px;
        font-weight:bold;
        text-align:left;
    }

    .legend-circle{
        width:20px;
        height:20px;
        border-radius:50%;
        display:inline-block;
        margin-right:8px;
    }

    .l1{ background:#ffdcdc; }
    .l2{ background:#ffc266; }
    .l3{ background:#ff8c00; }
    .l4{ background:#ff5500; }

    .footer{
        margin-top:15px;
        font-size:10px;
        text-align:right;
        color:#666;
    }
</style>

</head>

<body>

<table class="main-table">

    <!-- Title -->
    <tr>
        <td colspan="8" class="title">
            Employee Skill Matrix
        </td>
    </tr>

    <!-- Main Header -->
    <tr class="header">

        <th rowspan="2" width="5%">
            NO.
        </th>

        <th rowspan="2" width="30%">
            EMPLOYEE NAME
        </th>

        <th rowspan="2" width="10%">
            EMP NO.
        </th>

        <th rowspan="2" width="15%">
            DATE HIRED
        </th>

        <th colspan="4" class="department">
            DEPARTMENT NAME
        </th>

    </tr>

    <!-- Skill Headers -->
    <tr class="skill-header">

        <th width="10%">
            ASSEMBLY<br>PROCESS
        </th>

        <th width="10%">
            VISUAL<br>INSPECTION
        </th>

        <th width="10%">
            PARTS<br>PREP.
        </th>

        <th width="10%">
            MACHINE<br>OPERATION
        </th>

    </tr>

    <!-- Sample Rows -->
    @for($i = 1; $i <= 15; $i++)

    <tr>

        <td>{{ $i }}</td>

        <td class="employee"></td>

        <td></td>

        <td></td>

        <td>
            <span class="circle"></span>
        </td>

        <td>
            <span class="circle"></span>
        </td>

        <td>
            <span class="circle"></span>
        </td>

        <td>
            <span class="circle"></span>
        </td>

    </tr>

    @endfor

</table>

<br>

<table class="legend-table">

    <tr>

        <td width="20%" class="legend-title">
            Legend
        </td>

        <td width="20%">
            <span class="legend-circle l1"></span>
            Level 1 - Awareness
        </td>

        <td width="20%">
            <span class="legend-circle l2"></span>
            Level 2 - Knowledgeable
        </td>

        <td width="20%">
            <span class="legend-circle l3"></span>
            Level 3 - Can Perform Independently
        </td>

        <td width="20%">
            <span class="legend-circle l4"></span>
            Level 4 - Can Train Others
        </td>

    </tr>

</table>

<div class="footer">
    Generated by Training Records Database System
</div>


</body>
</html>
